### ISSUE TITLE
Content size cannot be arbitrarily picked.

### ISSUE THREAD

**Issue by GreenpantsDeveloper** [Aaditya-Singh/SAFIN#3]
Hi, first time creating an issue here. I love the project; the results look great!

Unfortunately, when I set the `content_size` to anything other than a power of two, I need to be lucky if the image size will work. Any idea how this can be helped, to make it run on arbitrary image sizes? Setting for instance `content_size` to 500, or 491, I get a RuntimeError referring to the tensor sizes. However, setting `content_size` to 497, all images _can_ be stylized. Interestingly, it appears that this behaviour only occurs for certain content sizes, not for style sizes (but don't quote me on that). Here's an I/O example using the provided input and style images:

```
python test.py --content_dir input/content --style_dir input/style --content_size 491 --net_file wave_net
```

```
File "C:\[USER_DIRECTORY]\SAFIN-main\utils.py", line 64, in forward
    return self.LL(ll) + self.LH(lh) + self.HL(hl) + self.HH(hh)
RuntimeError: The size of tensor a (488) must match the size of tensor b (490) at non-singleton dimension 3
```

I can't find where in the code the rules for input shapes are (implicitly) defined. Can you help me and potentially others? It would even help to know beforehand which values for an image width and height are going to work. Ideally, rectangular images of any size would function by default.

**Comment by Aaditya-Singh** [comment]
Thanks for your comments! Based on my understanding, this issue arises (possibly) due to the use of `WavePool` and `WaveUnpool` classes in the file `utils.py`. For specific sizes the `lh, hl, and hh` components are of odd spatial dimensions, but that isn't the case with the `ll` component because it is made from upsampling with a kernel of size and stride 2. For now, I've added a `reshape` function in the `WaveUnpool` class which makes the shape of all components the same as `ll`. We'll update the code with a better fix if we find one.

**Comment by GreenpantsDeveloper** [comment]
Thanks @Aaditya-Singh, that's a decent solution (and incredibly quick)!
I had already found that any width or height `n` where `n%8 == 0 or n%8 == 1` would work, but your solution is easier to work with.
